package com.cnrmall.springboot.dao;

import com.cnrmall.springboot.entity.VoteDO;
import org.apache.ibatis.annotations.Param;

public interface VoteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated Wed Nov 13 09:21:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated Wed Nov 13 09:21:40 CST 2019
     */
    int insert(VoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated Wed Nov 13 09:21:40 CST 2019
     */
    int insertSelective(VoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated Wed Nov 13 09:21:40 CST 2019
     */
    VoteDO selectByPrimaryKey(Integer id);


    /**
     * 根据传入的微信昵称、性别、微信头像三个条件查询重复用户
     * （现在无法获取手机号，待可以获取之后便可根据手机号进行过滤筛选）
     * @Param("id") int id
     * */
    VoteDO selectByCondition(@Param("nickname") String nickname, @Param("gender")String gender, @Param("avatarUrl")String avatarUrl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated Wed Nov 13 09:21:40 CST 2019
     */
    int updateByPrimaryKeySelective(VoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated Wed Nov 13 09:21:40 CST 2019
     */
    int updateByPrimaryKey(VoteDO record);
}